# https://github.com/flxn/qrcode2stl
version: '2.4'

services:
  app:
    build: ./
    container_name: qrcode2stl
    restart: on-failure:5
    ports:
      - 8082:8080
    security_opt:
      - apparmor:docker-default
      - no-new-privileges
    cpu_shares: 100
    pids_limit: 100
    mem_limit: 256m
    memswap_limit: 64m
    mem_reservation: 64m
    read_only: true
